### ISSUE TITLE
Dispose error on hot reload

### ISSUE THREAD

**Issue by shayant98** [artflutter/flutter_awesome_select#8] opened 2022-02-05 02:26 UTC
During development i get the following error:
Dart Unhandled Exception: A S2MultiSelected<String> was used after being disposed.

how can i resolve this issue

**Comment by vasilich6107** [comment] 2022-02-06 06:46
@shayant98 could you provide a reproduction code?

**Comment by shayant98** [comment] 2022-02-08 16:19
Sure...

So i have a widget named "MultiSelectDropdown" that holds the configuration of flutter awesome select.

`class StepConsumables extends ViewModelWidget<ServiceFormViewModel> {
  const StepConsumables({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context, ServiceFormViewModel model) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        if (model.workorder.parts != null || model.workorder.parts!.isNotEmpty)
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              SectionTitle(title: "Parts & consumables"),
              verticalSpaceSmall,
              MultiSelectDropdown(
                items: [...model.workorder.parts!.map((e) => S2Choice(value: e.id, title: e.part.description))],
                onChange: model.setPartsUsed,
                selecteditems: model.workorder.parts ?? [],
                title: "Parts",
              ),
              verticalSpaceMedium
            ],
          ),
        MultiSelectDropdown(
          items: [...actionsList.map((e) => S2Choice(value: e, title: e))],
          onChange: model.setSelectedItems,
          selecteditems: model.selectedActions,
          title: "Actions",
        ),
        verticalSpaceMedium
      ],
    );
  }
}`

This is the implementation of MultiSelectDropdown

class MultiSelectDropdown extends StatelessWidget {
  final List<S2Choice> items;
  final String title;
  final Function(List<dynamic>) onChange;
  final List<dynamic> selecteditems;
  const MultiSelectDropdown({Key? key, required this.items, required this.onChange, required this.selecteditems, required this.title}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SmartSelect<dynamic>.multiple(
      modalFilter: true,
      modalFilterAuto: true,
      modalValidation: (state) {
        if (state.value!.isEmpty) {
          return "please select actions";
        }
        return "";
      },
      modalConfig: S2ModalConfig(
        title: title,
        type: S2ModalType.bottomSheet,
        headerStyle: const S2ModalHeaderStyle(
          textStyle: kHeadingTextStyle,
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.only(topLeft: Radius.circular(10), topRight: Radius.circular(10))),
        ),
        style: const S2ModalStyle(
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.only(topLeft: Radius.circular(10), topRight: Radius.circular(10))),
        ),
      ),
      tileBuilder: (_, state) => Container(
        padding: EdgeInsets.symmetric(horizontal: 8),
        decoration: BoxDecoration(border: Border.all(color: Colors.grey), borderRadius: BorderRadius.circular(10)),
        child: S2Tile(
          value: Container(),
          onTap: state.showModal,
          title: Text(
            title,
            style: kHeadingTextStyle.copyWith(fontWeight: FontWeight.normal, color: Colors.grey.shade700),
          ),
          padding: EdgeInsets.zero,
          body: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              if (state.selected!.isNotEmpty)
                ...state.selected!.value!.map((e) => Column(
                      children: [
                        Row(
                          children: [
                            Icon(
                              Icons.check,
                              size: 20,
                              color: kPrimary,
                            ),
                            horizontalSpaceTiny,
                            Expanded(
                              child: Text(
                                e!,
                                style: kBody2TextStyle,
                              ),
                            ),
                          ],
                        ),
                        verticalSpaceTiny,
                      ],
                    ))
            ],
          ),
        ),
      ),
      validation: (state) {
        if (state.value == null) {
          return "Please select action";
        }
        return "";
      },
      selectedValue: selecteditems,
      choiceItems: items,
      onChange: (state) => onChange(state?.value ?? []),
    );



Some more info:
Flutter version 2.8.1
State Management Library: Stacked 2.2.8

**Comment by vasilich6107** [comment] 2022-02-08 17:04
@shayant98 
Wrap your code samples with code bloc. 

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks


It is impossible to read now

**Comment by vasilich6107** [comment] 2022-04-02 14:50
@shayant98 here is the errors that I see when I try to copy paste you samples
Could you make your code runnable?

<img width="636" alt="image" src="https://user-images.githubusercontent.com/6721286/161388732-7f9969db-4feb-4eba-8f39-ff292991a923.png">

**Comment by vasilich6107** [comment] 2022-05-27 18:26
Closing issue due to the missing reproduction
Feel free to reopen with runnable reproduction code

**Closed by vasilich6107** 2022-05-27 18:26 UTC
