### ISSUE TITLE
Null check operator used on a null value when use choiceType: S2ChoiceType.chips

### ISSUE THREAD

**Issue by limsocheat** [artflutter/flutter_awesome_select#13] opened 2022-04-01 03:08 UTC
```
SmartSelect<String?>.single(
    key: _timeKey,
    title: 'Selected time'.tr,
    choiceItems: controller.times.map((time) {
      return S2Choice(
        value: time.value,
        title: time.text,
        group: time.name,
      );
    }).toList(),
    selectedValue: field.value,
    onChange: (selected) => field.didChange(selected.value),
    modalType: S2ModalType.bottomSheet,
    modalTitle: 'Select the reservation time'.tr,
    choiceType: S2ChoiceType.chips,
    choiceDirection: Axis.horizontal,
    choiceStyle: S2ChoiceStyle(
      outlined: true,
      shape: RoundedRectangleBorder(
        borderRadius: const BorderRadius.all(Radius.circular(5)),
        side: BorderSide(
          color: Colors.grey.shade300,
        ),
      ),
    ),
    choiceActiveStyle: const S2ChoiceStyle(
      color: Colors.black,
      raised: true,
    ),
    groupEnabled: true,
    groupHeaderBuilder: (context, state, group) {
      return Container(
        color: ColorConfig.gold,
        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 10),
        alignment: Alignment.centerLeft,
        child: S2Text(
          text: group.name?.toUpperCase(),
          style: const TextStyle(
            color: Colors.white,
            fontWeight: FontWeight.bold,
          ),
        ),
      );
    },
    groupBuilder: (context, state, group) {
      return StickyHeader(
        header: state.groupHeader(group),
        content: state.groupChoices(group),
      );
    },
    tileBuilder: (context, state) {
      return S2Tile.fromState(
        state,
        isLoading: controller.loadingTimes.value,
        loadingText: 'loading'.tr,
        isError: field.errorText != null,
        body: ConditionalBuilder(
          condition: field.errorText != null,
          builder: (context) => Padding(
            padding: const EdgeInsets.only(left: 15.0),
            child: Text(
              '${field.errorText}',
              style: Theme.of(context).textTheme.caption?.copyWith(
                    color: Colors.red,
                  ),
            ),
          ),
        ),
      );
    },
  )
```

![Simulator Screen Shot - iPhone 13 Pro Max - 2022-04-01 at 10 08 22](https://user-images.githubusercontent.com/6656644/161187661-524447c4-e690-423c-a57f-cae28cfbf008.png)

**Comment by vasilich6107** [comment] 2022-04-02 14:47
@limsocheat could you provide an example which can be copy pasted and tested
this one is runnable

**Comment by vasilich6107** [comment] 2022-04-02 14:56
This is the errors that I see when copy paste into example project for reproduction

<img width="552" alt="image" src="https://user-images.githubusercontent.com/6721286/161388946-8b2e3bc3-7cfe-4388-9fa3-92c0f6fcb8af.png">

**Comment by chrisvidal** [comment] 2022-04-04 04:29
same issue with ` flutter_awesome_select: ^6.1.2-beta` and `S2Chips` used in `S2Tile.fromState(`

somehow with the beta version, `state.selected.choice` is null

**Comment by vasilich6107** [comment] 2022-04-04 06:23
@chrisvidal Could you provide working reproduction code?

**Comment by chrisvidal** [comment] 2022-04-04 06:27
sorry I don't have time to create a specific code for this :(
It was working fine before updating to the `flutter_awesome_select: ^6.1.2-beta`

my code is directly inherited from the examples actually with single choice with modal sheet selection

**Comment by vasilich6107** [comment] 2022-05-27 18:26
Closing issue due to the missing reproduction
Feel free to reopen with runnable reproduction code

**Closed by vasilich6107** 2022-05-27 18:26 UTC
